Revert "HOSTDEV-1717 Replace platform.dist with linux_distribution"
This reverts commit f713d5faedd28702759f71675f22f90ecd090905, because it breaks CentOS:
Downloading ftp://python.infinidat.com/python/python-v2.7.6.13-linux-centoslinux-7-x64.tar.gz

stderr=While:
  Installing isolated-python.
Error: Error downloading extends for URL ftp://python.infinidat.com/python/python-v2.7.6.13-linux-centoslinux-7-x64.tar.gz: [Errno ftp error] [Errno ftp error] 550 Failed to change directory.